apiVersion: gke.cattle.io/v1
kind: GKEClusterConfig
metadata:
  name: example-autopilot-cluster
spec:
  clusterName: "example-autopilot-cluster"
  description: "example autopilot cluster"
  region: "us-west1"
  projectID: "example-project"
  kubernetesVersion: "1.18.16-gke.302"
  loggingService: ""
  monitoringService: ""
  enableKubernetesAlpha: false
  clusterIpv4Cidr: "10.42.0.0/16"
  ipAllocationPolicy:
    useIpAliases: true
  nodePools: []
  clusterAddons:
    httpLoadBalancing: true
    networkPolicyConfig: false
    horizontalPodAutoscaling: true
  networkPolicyEnabled: false
  network: default
  subnetwork: default
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: false
  masterAuthorizedNetworks:
    enabled: false
  locations: []
  maintenanceWindow: ""
  autopilot: true
  googleCredentialSecret: "cattle-global-data:cc-abcde"
