apiVersion: gke.cattle.io/v1
kind: GKEClusterConfig
metadata:
  name: example-cluster
spec:
  clusterName: "example-cluster"
  description: "example cluster"
  labels: {}
  region: "us-west1"
  projectID: "example-project"
  kubernetesVersion: "1.19.10-gke.1600"
  loggingService: ""
  monitoringService: ""
  enableKubernetesAlpha: false
  clusterIpv4Cidr: "10.42.0.0/16"
  ipAllocationPolicy:
    useIpAliases: true
  nodePools:
  - name: example-node-pool
    autoscaling:
      enabled: false
    config: {}
    labels: []
    initialNodeCount: 1
    maxPodsConstraint: 110
    version: "1.19.10-gke.1600"
    management:
      autoRepair: true
      autoUpgrade: true
  clusterAddons:
    httpLoadBalancing: true
    networkPolicyConfig: false
    horizontalPodAutoscaling: true
  networkPolicyEnabled: false
  network: default
  subnetwork: default
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: false
  masterAuthorizedNetworks:
    enabled: false
  locations: []
  maintenanceWindow: ""
  googleCredentialSecret: "cattle-global-data:cc-abcde"
