apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gkeclusterconfigs.gke.cattle.io
spec:
  group: gke.cattle.io
  names:
    kind: GKEClusterConfig
    plural: gkeclusterconfigs
    shortNames:
    - gkecc
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            clusterAddons:
              properties:
                horizontalPodAutoscaling:
                  nullable: true
                  type: boolean
                httpLoadBalancing:
                  nullable: true
                  type: boolean
                kubernetesDashboard:
                  nullable: true
                  type: boolean
                networkPolicyConfig:
                  nullable: true
                  type: boolean
              type: object
            clusterIpv4Cidr:
              nullable: true
              type: string
            clusterName:
              nullable: true
              type: string
            credentialContent:
              nullable: true
              type: string
            description:
              nullable: true
              type: string
            enableAlphaFeature:
              nullable: true
              type: boolean
            imported:
              type: boolean
            kubernetesVersion:
              nullable: true
              type: string
            loggingTypes:
              items:
                nullable: true
                type: string
              nullable: true
              type: array
            nodePools:
              items:
                properties:
                  autoscaling:
                    nullable: true
                    properties:
                      enabled:
                        nullable: true
                        type: boolean
                      maxNodeCount:
                        nullable: true
                        type: integer
                      minNodeCount:
                        nullable: true
                        type: integer
                    type: object
                  config:
                    nullable: true
                    properties:
                      diskSizeGb:
                        nullable: true
                        type: integer
                      diskType:
                        nullable: true
                        type: string
                      imageType:
                        nullable: true
                        type: string
                      labels:
                        additionalProperties:
                          nullable: true
                          type: string
                        nullable: true
                        type: object
                      localSsdCount:
                        nullable: true
                        type: integer
                      machineType:
                        nullable: true
                        type: string
                      preemptible:
                        nullable: true
                        type: boolean
                      taints:
                        items:
                          properties:
                            effect:
                              nullable: true
                              type: string
                            key:
                              nullable: true
                              type: string
                            value:
                              nullable: true
                              type: string
                          type: object
                        nullable: true
                        type: array
                    type: object
                  initialNodeCount:
                    nullable: true
                    type: integer
                  maxPodsConstraint:
                    nullable: true
                    type: integer
                  name:
                    nullable: true
                    type: string
                  version:
                    nullable: true
                    type: string
                type: object
              nullable: true
              type: array
            projectID:
              nullable: true
              type: string
            region:
              nullable: true
              type: string
            secretsEncryption:
              nullable: true
              type: boolean
            securityGroups:
              items:
                nullable: true
                type: string
              nullable: true
              type: array
            serviceRole:
              nullable: true
              type: string
            subnets:
              items:
                nullable: true
                type: string
              nullable: true
              type: array
            tags:
              additionalProperties:
                nullable: true
                type: string
              nullable: true
              type: object
            zone:
              nullable: true
              type: string
          type: object
        status:
          properties:
            failureMessage:
              nullable: true
              type: string
            networkFieldsSource:
              nullable: true
              type: string
            phase:
              nullable: true
              type: string
            securityGroups:
              items:
                nullable: true
                type: string
              nullable: true
              type: array
            subnets:
              items:
                nullable: true
                type: string
              nullable: true
              type: array
            virtualNetwork:
              nullable: true
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
